package jMoria.game.monster;

public enum MonsterType {
  FILTHY_STREET_URCHIN("Filthy Street Urchin"),
  BLUBBERING_IDIOT("Blubbering Idiot"),
  PITIFUL_LOOKING_BEGGAR("Pitiful-Looking Beggar"),
  MANGY_LOOKING_LEPER("Mangy-Looking Leper"),
  SQUINT_EYED_ROGUE("Squint-Eyed Rogue"),
  SINGING_HAPPY_DRUNK("Singing, Happy Drunk"),
  MEAN_LOOKING_MERCENARY("Mean-Looking Mercenary"),
  BATTLE_SCARRED_VETERAN("Battle-Scarred Veteran"),
  GREY_MUSHROOM_PATCH("Grey Mushroom patch"),
  GIANT_YELLOW_CENTIPEDE("Giant Yellow Centipede"),
  GIANT_WHITE_CENTIPEDE("Giant White Centipede"),
  WHITE_ICKY_THING("White Icky-Thing"),
  CLEAR_ICKY_THING("Clear Icky-Thing"),
  GIANT_WHITE_MOUSE("Giant White Mouse"),
  LARGE_BROWN_SNAKE("Large Brown Snake"),
  LARGE_WHITE_SNAKE("Large White Snake"),
  KOBOLD("Kobold"),
  WHITE_WORM_MASS("White Worm mass"),
  FLOATING_EYE("Floating Eye"),
  SHRIEKER_MUSHROOM_PATCH("Shrieker Mushroom patch"),
  BLUBBERING_ICKY_THING("Blubbering Icky-Thing"),
  METALLIC_GREEN_CENTIPEDE("Metallic Green Centipede"),
  NOVICE_WARRIOR("Novice Warrior"),
  NOVICE_ROGUE("Novice Rogue"),
  NOVICE_PRIEST("Novice Priest"),
  NOVICE_MAGE("Novice Mage"),
  YELLOW_MUSHROOM_PATCH("Yellow Mushroom patch"),
  WHITE_JELLY("White Jelly"),
  GIANT_GREEN_FROG("Giant Green Frog"),
  GIANT_BLACK_ANT("Giant Black Ant"),
  WHITE_HARPY("White Harpy"),
  BLUE_YEEK("Blue Yeek"),
  GREEN_WORM_MASS("Green Worm mass"),
  LARGE_BLACK_SNAKE("Large Black Snake"),
  POLTERGEIST("Poltergeist"),
  METALLIC_BLUE_CENTIPEDE("Metallic Blue Centipede"),
  GIANT_WHITE_LOUSE("Giant White Louse"),
  BLACK_NAGA("Black Naga"),
  SPOTTED_MUSHROOM_PATCH("Spotted Mushroom patch"),
  YELLOW_JELLY("Yellow Jelly"),
  SCRUFFY_LOOKING_HOBBIT("Scruffy-Looking Hobbit"),
  HUGE_BROWN_BAT("Huge Brown Bat"),
  GIANT_WHITE_ANT("Giant White Ant"),
  YELLOW_MOLD("Yellow Mold"),
  METALLIC_RED_CENTIPEDE("Metallic Red Centipede"),
  YELLOW_WORM_MASS("Yellow Worm mass"),
  LARGE_GREEN_SNAKE("Large Green Snake"),
  RADIATION_EYE("Radiation Eye"),
  DROOLING_HARPY("Drooling Harpy"),
  SILVER_MOUSE("Silver Mouse"),
  BLACK_MUSHROOM_PATCH("Black Mushroom patch"),
  BLUE_JELLY("Blue Jelly"),
  CREEPING_COPPER_COINS("Creeping Copper Coins"),
  GIANT_WHITE_RAT("Giant White Rat"),
  GIANT_BLACK_CENTIPEDE("Giant Black Centipede"),
  GIANT_BLUE_CENTIPEDE("Giant Blue Centipede"),
  BLUE_WORM_MASS("Blue Worm mass"),
  LARGE_GREY_SNAKE("Large Grey Snake"),
  JACKAL("Jackal"),
  GREEN_NAGA("Green Naga"),
  GREEN_GLUTTON_GHOST("Green Glutton Ghost"),
  WHITE_MUSHROOM_PATCH("White Mushroom patch"),
  GREEN_JELLY("Green Jelly"),
  SKELETON_KOBOLD("Skeleton Kobold"),
  SILVER_JELLY("Silver Jelly"),
  GIANT_BLACK_FROG("Giant Black Frog"),
  GREY_ICKY_THING("Grey Icky-Thing"),
  DISENCHANTER_EYE("Disenchanter Eye"),
  BLACK_YEEK("Black Yeek"),
  RED_WORM_MASS("Red Worm mass"),
  GIANT_HOUSE_FLY("Giant House Fly"),
  COPPERHEAD_SNAKE("Copperhead Snake"),
  ROT_JELLY("Rot Jelly"),
  PURPLE_MUSHROOM_PATCH("Purple Mushroom patch"),
  BROWN_MOLD("Brown Mold"),
  GIANT_BROWN_BAT("Giant Brown Bat"),
  CREEPING_SILVER_COINS("Creeping Silver Coins"),
  ORC("Orc"),
  GREY_HARPY("Grey Harpy"),
  BLUE_ICKY_THING("Blue Icky-Thing"),
  RATTLESNAKE("Rattlesnake"),
  BLOODSHOT_EYE("Bloodshot Eye"),
  RED_NAGA("Red Naga"),
  RED_JELLY("Red Jelly"),
  GIANT_RED_FROG("Giant Red Frog"),
  GREEN_ICKY_THING("Green Icky-Thing"),
  ZOMBIE_KOBOLD("Zombie Kobold"),
  LOST_SOUL("Lost Soul"),
  GREEDY_LITTLE_GNOME("Greedy Little Gnome"),
  GIANT_GREEN_FLY("Giant Green Fly"),
  BROWN_YEEK("Brown Yeek"),
  GREEN_MOLD("Green Mold"),
  SKELETON_ORC("Skeleton Orc"),
  SEEDY_LOOKING_HUMAN("Seedy Looking Human"),
  RED_ICKY_THING("Red Icky-Thing"),
  BANDIT("Bandit"),
  YETI("Yeti"),
  BLOODSHOT_ICKY_THING("Bloodshot Icky-Thing"),
  GIANT_GREY_RAT("Giant Grey Rat"),
  BLACK_HARPY("Black Harpy"),
  GIANT_BLACK_BAT("Giant Black Bat"),
  CLEAR_YEEK("Clear Yeek"),
  ORC_SHAMAN("Orc Shaman"),
  GIANT_RED_ANT("Giant Red Ant"),
  KING_COBRA("King Cobra"),
  CLEAR_MUSHROOM_PATCH("Clear Mushroom patch"),
  GIANT_WHITE_TICK("Giant White Tick"),
  HAIRY_MOLD("Hairy Mold"),
  DISENCHANTER_MOLD("Disenchanter Mold"),
  GIANT_RED_CENTIPEDE("Giant Red Centipede"),
  CREEPING_GOLD_COINS("Creeping Gold Coins"),
  GIANT_FRUIT_FLY("Giant Fruit Fly"),
  BRIGAND("Brigand"),
  ORC_ZOMBIE("Orc Zombie"),
  ORC_WARRIOR("Orc Warrior"),
  VORPAL_BUNNY("Vorpal Bunny"),
  NASTY_LITTLE_GNOME("Nasty Little Gnome"),
  HOBGOBLIN("Hobgoblin"),
  BLACK_MAMBA("Black Mamba"),
  GRAPE_JELLY("Grape Jelly"),
  MASTER_YEEK("Master Yeek"),
  PRIEST("Priest"),
  GIANT_CLEAR_ANT("Giant Clear Ant"),
  AIR_SPIRIT("Air Spirit"),
  SKELETON_HUMAN("Skeleton Human"),
  HUMAN_ZOMBIE("Human Zombie"),
  MOANING_SPIRIT("Moaning Spirit"),
  SWORDSMAN("Swordsman"),
  KILLER_BROWN_BEETLE("Killer Brown Beetle"),
  OGRE("Ogre"),
  GIANT_RED_SPECKLED_FROG("Giant Red Speckled Frog"),
  MAGIC_USER("Magic User"),
  BLACK_ORC("Black Orc"),
  GIANT_LONG_EARED_BAT("Giant Long-Eared Bat"),
  GIANT_GNAT("Giant Gnat"),
  KILLER_GREEN_BEETLE("Killer Green Beetle"),
  GIANT_FLEA("Giant Flea"),
  GIANT_WHITE_DRAGON_FLY("Giant White Dragon Fly"),
  HILL_GIANT("Hill Giant"),
  SKELETON_HOBGOBLIN("Skeleton Hobgoblin"),
  FLESH_GOLEM("Flesh Golem"),
  WHITE_DRAGON_BAT("White Dragon Bat"),
  GIANT_BLACK_LOUSE("Giant Black Louse"),
  GUARDIAN_NAGA("Guardian Naga"),
  GIANT_GREY_BAT("Giant Grey Bat"),
  GIANT_CLEAR_CENTIPEDE("Giant Clear Centipede"),
  GIANT_YELLOW_TICK("Giant Yellow Tick"),
  GIANT_EBONY_ANT("Giant Ebony Ant"),
  FROST_GIANT("Frost Giant"),
  CLAY_GOLEM("Clay Golem"),
  HUGE_WHITE_BAT("Huge White Bat"),
  GIANT_TAN_BAT("Giant Tan Bat"),
  VIOLET_MOLD("Violet Mold"),
  UMBER_HULK("Umber Hulk"),
  GELATINOUS_CUBE("Gelatinous Cube"),
  GIANT_BLACK_RAT("Giant Black Rat"),
  GIANT_GREEN_DRAGON_FLY("Giant Green Dragon Fly"),
  FIRE_GIANT("Fire Giant"),
  GREEN_DRAGON_BAT("Green Dragon Bat"),
  QUASIT("Quasit"),
  TROLL("Troll"),
  WATER_SPIRIT("Water Spirit"),
  GIANT_BROWN_SCORPION("Giant Brown Scorpion"),
  EARTH_SPIRIT("Earth Spirit"),
  FIRE_SPIRIT("Fire Spirit"),
  URUK_HAI_ORC("Uruk-Hai Orc"),
  STONE_GIANT("Stone Giant"),
  STONE_GOLEM("Stone Golem"),
  GREY_OOZE("Grey Ooze"),
  DISENCHANTER_OOZE("Disenchanter Ooze"),
  GIANT_SPOTTED_RAT("Giant Spotted Rat"),
  MUMMIFIED_KOBOLD("Mummified Kobold"),
  KILLER_BLACK_BEETLE("Killer Black Beetle"),
  RED_MOLD("Red Mold"),
  QUYLTHULG("Quylthulg"),
  GIANT_RED_BAT("Giant Red Bat"),
  GIANT_BLACK_DRAGON_FLY("Giant Black Dragon Fly"),
  CLOUD_GIANT("Cloud Giant"),
  BLACK_DRAGON_BAT("Black Dragon Bat"),
  BLUE_DRAGON_BAT("Blue Dragon Bat"),
  MUMMIFIED_ORC("Mummified Orc"),
  KILLER_BORING_BEETLE("Killer Boring Beetle"),
  KILLER_STAG_BEETLE("Killer Stag Beetle"),
  BLACK_MOLD("Black Mold"),
  IRON_GOLEM("Iron Golem"),
  GIANT_YELLOW_SCORPION("Giant Yellow Scorpion"),
  GREEN_OOZE("Green Ooze"),
  BLACK_OOZE("Black Ooze"),
  WARRIOR("Warrior"),
  RED_DRAGON_BAT("Red Dragon Bat"),
  KILLER_BLUE_BEETLE("Killer Blue Beetle"),
  GIANT_SILVER_ANT("Giant Silver Ant"),
  CRIMSON_MOLD("Crimson Mold"),
  FOREST_WIGHT("Forest Wight"),
  BERZERKER("Berzerker"),
  MUMMIFIED_HUMAN("Mummified Human"),
  BANSHEE("Banshee"),
  GIANT_TROLL("Giant Troll"),
  GIANT_BROWN_TICK("Giant Brown Tick"),
  KILLER_RED_BEETLE("Killer Red Beetle"),
  WOODEN_MOLD("Wooden Mold"),
  GIANT_BLUE_DRAGON_FLY("Giant Blue Dragon Fly"),
  GIANT_GREY_ANT_LION("Giant Grey Ant Lion"),
  DISENCHANTER_BAT("Disenchanter Bat"),
  GIANT_FIRE_TICK("Giant Fire Tick"),
  WHITE_WRAITH("White Wraith"),
  GIANT_BLACK_SCORPION("Giant Black Scorpion"),
  CLEAR_OOZE("Clear Ooze"),
  KILLER_FIRE_BEETLE("Killer Fire Beetle"),
  VAMPIRE("Vampire"),
  GIANT_RED_DRAGON_FLY("Giant Red Dragon Fly"),
  SHIMMERING_MOLD("Shimmering Mold"),
  BLACK_KNIGHT("Black Knight"),
  MAGE("Mage"),
  ICE_TROLL("Ice Troll"),
  GIANT_PURPLE_WORM("Giant Purple Worm"),
  YOUNG_BLUE_DRAGON("Young Blue Dragon"),
  YOUNG_WHITE_DRAGON("Young White Dragon"),
  YOUNG_GREEN_DRAGON("Young Green Dragon"),
  GIANT_FIRE_BAT("Giant Fire Bat"),
  GIANT_GLOWING_RAT("Giant Glowing Rat"),
  SKELETON_TROLL("Skeleton Troll"),
  GIANT_LIGHTNING_BAT("Giant Lightning Bat"),
  GIANT_STATIC_ANT("Giant Static Ant"),
  GRAVE_WIGHT("Grave Wight"),
  KILLER_SLICER_BEETLE("Killer Slicer Beetle"),
  GIANT_WHITE_ANT_LION("Giant White Ant Lion"),
  GHOST("Ghost"),
  GIANT_BLACK_ANT_LION("Giant Black Ant Lion"),
  DEATH_WATCH_BEETLE("Death Watch Beetle"),
  OGRE_MAGE("Ogre Mage"),
  TWO_HEADED_TROLL("Two-Headed Troll"),
  INVISIBLE_STALKER("Invisible Stalker"),
  GIANT_HUNTER_ANT("Giant Hunter Ant"),
  NINJA("Ninja"),
  BARROW_WIGHT("Barrow Wight"),
  SKELETON_2_HEADED_TROLL("Skeleton 2-Headed Troll"),
  WATER_ELEMENTAL("Water Elemental"),
  FIRE_ELEMENTAL("Fire Elemental"),
  LICH("Lich"),
  MASTER_VAMPIRE("Master Vampire"),
  SPIRIT_TROLL("Spirit Troll"),
  GIANT_RED_SCORPION("Giant Red Scorpion"),
  EARTH_ELEMENTAL("Earth Elemental"),
  YOUNG_BLACK_DRAGON("Young Black Dragon"),
  YOUNG_RED_DRAGON("Young Red Dragon"),
  NECROMANCER("Necromancer"),
  MUMMIFIED_TROLL("Mummified Troll"),
  GIANT_RED_ANT_LION("Giant Red Ant Lion"),
  MATURE_WHITE_DRAGON("Mature White Dragon"),
  XORN("Xorn"),
  GIANT_MOTTLED_ANT_LION("Giant Mottled Ant Lion"),
  GREY_WRAITH("Grey Wraith"),
  YOUNG_MULTI_HUED_DRAGON("Young Multi-Hued Dragon"),
  MATURE_BLUE_DRAGON("Mature Blue Dragon"),
  MATURE_GREEN_DRAGON("Mature Green Dragon"),
  IRIDESCENT_BEETLE("Iridescent Beetle"),
  KING_VAMPIRE("King Vampire"),
  KING_LICH("King Lich"),
  MATURE_RED_DRAGON("Mature Red Dragon"),
  MATURE_BLACK_DRAGON("Mature Black Dragon"),
  MATURE_MULTI_HUED_DRAGON("Mature Multi-Hued Dragon"),
  ANCIENT_WHITE_DRAGON("Ancient White Dragon"),
  EMPEROR_WIGHT("Emperor Wight"),
  BLACK_WRAITH("Black Wraith"),
  NETHER_WRAITH("Nether Wraith"),
  SORCERER("Sorcerer"),
  ANCIENT_BLUE_DRAGON("Ancient Blue Dragon"),
  ANCIENT_GREEN_DRAGON("Ancient Green Dragon"),
  ANCIENT_BLACK_DRAGON("Ancient Black Dragon"),
  CRYSTAL_OOZE("Crystal Ooze"),
  DISENCHANTER_WORM("Disenchanter Worm"),
  ROTTING_QUYLTHULG("Rotting Quylthulg"),
  ANCIENT_RED_DRAGON("Ancient Red Dragon"),
  DEATH_QUASIT("Death Quasit"),
  EMPEROR_LICH("Emperor Lich"),
  ANCIENT_MULTI_HUED_DRAGON("Ancient Multi-Hued Dragon"),
  EVIL_IGGY("Evil Iggy"),
  BALROG("Balrog");

  public final String name;

  MonsterType(String name) {
    this.name = name;
  }
}
